repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.12
    hooks:
      - id: ruff
        args: ["--fix"]
      - id: ruff-format

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-merge-conflict
      - id: debug-statements
      - id: check-added-large-files
        args: ["--maxkb=999"]

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.2.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: [feat, fix, docs, style, refactor, perf, test, build, ci, chore, revert]

  # - repo: local
  #   hooks:
  #     - id: branch-name-check
  #       name: Branch name convention check
  #       language: system
  #       entry: >
  #         bash -c '[[ "$(git rev-parse --abbrev-ref HEAD)" =~ ^(feat|fix|chore|task|refactor|docs|test)(\(#?[0-9]+\))?-[a-z0-9\-]+$ ]] || (echo "Branch name must match: <type>(#<issue>)-<short-description>" && exit 1)'
  #       always_run: true
  #       pass_filenames: false
